### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Stephanech** [NovaFox161/PerWorldChatPlus#4]
When the server starts, this appears in the console:

11.02 17:01:29 [Server] WARN [Fatal Error] :58:86: The reference to entity "render" must end with the ';' delimiter.
11.02 17:01:29 [Server] WARN [PerWorldChatPlus] Update URL is invalid! Report this to Shades161 on her Dev Bukkit Page!

The server is terribly lagged thought, but I can't confirm if it's because of this

Spigot 1.12
Plugin version: 5.1.1

**Comment by NovaFox161** [comment]
This is a known issue with the auto updater. It has been fixed in recent code changes but not pushed out into a release. It causes no harm to the plugin or the server, just an annoyance and prevents notifications about new releases. 

An update will be coming where this and many other issues are fully patched.
